// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/kafka/event.proto

package kafkapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KafkaEvent matches connection/internal/platform/kafka/event.go.
type KafkaEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,json=ID,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=UserID,proto3" json:"user_id,omitempty"`
	RoomId        uint32                 `protobuf:"varint,3,opt,name=room_id,json=RoomID,proto3" json:"room_id,omitempty"`
	MsgType       string                 `protobuf:"bytes,4,opt,name=msg_type,json=MsgType,proto3" json:"msg_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,json=Content,proto3" json:"content,omitempty"`
	TempId        string                 `protobuf:"bytes,6,opt,name=temp_id,json=TempID,proto3" json:"temp_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=CreateAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KafkaEvent) Reset() {
	*x = KafkaEvent{}
	mi := &file_proto_kafka_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KafkaEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaEvent) ProtoMessage() {}

func (x *KafkaEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kafka_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaEvent.ProtoReflect.Descriptor instead.
func (*KafkaEvent) Descriptor() ([]byte, []int) {
	return file_proto_kafka_event_proto_rawDescGZIP(), []int{0}
}

func (x *KafkaEvent) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KafkaEvent) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *KafkaEvent) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *KafkaEvent) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *KafkaEvent) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *KafkaEvent) GetTempId() string {
	if x != nil {
		return x.TempId
	}
	return ""
}

func (x *KafkaEvent) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_proto_kafka_event_proto protoreflect.FileDescriptor

const file_proto_kafka_event_proto_rawDesc = "" +
	"\n" +
	"\x17proto/kafka/event.proto\x12\bkafka.v1\"\xba\x01\n" +
	"\n" +
	"KafkaEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02ID\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06UserID\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\rR\x06RoomID\x12\x19\n" +
	"\bmsg_type\x18\x04 \x01(\tR\aMsgType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\aContent\x12\x17\n" +
	"\atemp_id\x18\x06 \x01(\tR\x06TempID\x12\x1c\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\bCreateAtB/Z-connection/internal/platform/kafka/pb;kafkapbb\x06proto3"

var (
	file_proto_kafka_event_proto_rawDescOnce sync.Once
	file_proto_kafka_event_proto_rawDescData []byte
)

func file_proto_kafka_event_proto_rawDescGZIP() []byte {
	file_proto_kafka_event_proto_rawDescOnce.Do(func() {
		file_proto_kafka_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kafka_event_proto_rawDesc), len(file_proto_kafka_event_proto_rawDesc)))
	})
	return file_proto_kafka_event_proto_rawDescData
}

var file_proto_kafka_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_kafka_event_proto_goTypes = []any{
	(*KafkaEvent)(nil), // 0: kafka.v1.KafkaEvent
}
var file_proto_kafka_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_kafka_event_proto_init() }
func file_proto_kafka_event_proto_init() {
	if File_proto_kafka_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kafka_event_proto_rawDesc), len(file_proto_kafka_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_kafka_event_proto_goTypes,
		DependencyIndexes: file_proto_kafka_event_proto_depIdxs,
		MessageInfos:      file_proto_kafka_event_proto_msgTypes,
	}.Build()
	File_proto_kafka_event_proto = out.File
	file_proto_kafka_event_proto_goTypes = nil
	file_proto_kafka_event_proto_depIdxs = nil
}
