// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v3.21.12
// source: proto/kafka/event.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "kafka.v1";

/** KafkaEvent matches connection/internal/platform/kafka/event.go. */
export interface KafkaEvent {
  id: string;
  userId: number;
  roomId: number;
  msgType: string;
  content: Uint8Array;
  tempId: string;
  createdAt: string;
}

function createBaseKafkaEvent(): KafkaEvent {
  return { id: "0", userId: 0, roomId: 0, msgType: "", content: new Uint8Array(0), tempId: "", createdAt: "0" };
}

export const KafkaEvent: MessageFns<KafkaEvent> = {
  encode(message: KafkaEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "0") {
      writer.uint32(8).uint64(message.id);
    }
    if (message.userId !== 0) {
      writer.uint32(16).uint32(message.userId);
    }
    if (message.roomId !== 0) {
      writer.uint32(24).uint32(message.roomId);
    }
    if (message.msgType !== "") {
      writer.uint32(34).string(message.msgType);
    }
    if (message.content.length !== 0) {
      writer.uint32(42).bytes(message.content);
    }
    if (message.tempId !== "") {
      writer.uint32(50).string(message.tempId);
    }
    if (message.createdAt !== "0") {
      writer.uint32(56).int64(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KafkaEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKafkaEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.userId = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.roomId = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.msgType = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.content = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.tempId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KafkaEvent {
    return {
      id: isSet(object.ID) ? globalThis.String(object.ID) : isSet(object.id) ? globalThis.String(object.id) : "0",
      userId: isSet(object.UserID)
        ? globalThis.Number(object.UserID)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      roomId: isSet(object.RoomID)
        ? globalThis.Number(object.RoomID)
        : isSet(object.room_id)
        ? globalThis.Number(object.room_id)
        : 0,
      msgType: isSet(object.MsgType)
        ? globalThis.String(object.MsgType)
        : isSet(object.msg_type)
        ? globalThis.String(object.msg_type)
        : "",
      content: isSet(object.Content)
        ? bytesFromBase64(object.Content)
        : isSet(object.content)
        ? bytesFromBase64(object.content)
        : new Uint8Array(0),
      tempId: isSet(object.TempID)
        ? globalThis.String(object.TempID)
        : isSet(object.temp_id)
        ? globalThis.String(object.temp_id)
        : "",
      createdAt: isSet(object.CreateAt)
        ? globalThis.String(object.CreateAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "0",
    };
  },

  toJSON(message: KafkaEvent): unknown {
    const obj: any = {};
    if (message.id !== "0") {
      obj.ID = message.id;
    }
    if (message.userId !== 0) {
      obj.UserID = Math.round(message.userId);
    }
    if (message.roomId !== 0) {
      obj.RoomID = Math.round(message.roomId);
    }
    if (message.msgType !== "") {
      obj.MsgType = message.msgType;
    }
    if (message.content.length !== 0) {
      obj.Content = base64FromBytes(message.content);
    }
    if (message.tempId !== "") {
      obj.TempID = message.tempId;
    }
    if (message.createdAt !== "0") {
      obj.CreateAt = message.createdAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KafkaEvent>, I>>(base?: I): KafkaEvent {
    return KafkaEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KafkaEvent>, I>>(object: I): KafkaEvent {
    const message = createBaseKafkaEvent();
    message.id = object.id ?? "0";
    message.userId = object.userId ?? 0;
    message.roomId = object.roomId ?? 0;
    message.msgType = object.msgType ?? "";
    message.content = object.content ?? new Uint8Array(0);
    message.tempId = object.tempId ?? "";
    message.createdAt = object.createdAt ?? "0";
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
